### ISSUE TITLE
Dragging main does not drag child windows when docked

### ISSUE THREAD

**Issue by aesalazar** [EikosPartners/windowmanagerjs#9]
Using the windowmanagerjsdemo application to create a child window will show the problem.  Dock the child with main.  If child is dragged main moves with it.  But if main is then dragged child does NOT move with it.  Go to drag child again and it will still drag main.

**Comment by Dillonu** [comment]
This is due to how windows behave with frames vs without frames.
To make docking and snapping work properly, we need to control how windows are dragged. So I've disabled the snap and dock system (e77f4ee) on framed windows (since we can't control the windows while dragging using the OS frame). Issue #10 will track improving frameless windows to ensure they have frames, and potentially find a way to re-enable the OS frames with the snap and dock system.
